INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (2,'Afeganistao'),
	 (3,'Africa Do Sul'),
	 (4,'Akrotiri'),
	 (5,'Albania'),
	 (6,'Alemanha'),
	 (7,'Andorra'),
	 (8,'Angola'),
	 (9,'Anguila'),
	 (10,'Antarctida'),
	 (11,'Antigua E Barbuda');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (12,'Antilhas Neerlandesas'),
	 (13,'Arabia Saudita'),
	 (14,'Arctic Ocean'),
	 (15,'Argelia'),
	 (16,'Argentina'),
	 (17,'Armenia'),
	 (18,'Aruba'),
	 (19,'Ashmore And Cartier Islands'),
	 (20,'Atlantic Ocean'),
	 (21,'Australia');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (22,'Austria'),
	 (23,'Azerbaijao'),
	 (24,'Baamas'),
	 (25,'Bangladeche'),
	 (26,'Barbados'),
	 (27,'Barem'),
	 (28,'Belgica'),
	 (29,'Belize'),
	 (30,'Benim'),
	 (31,'Bermudas');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (32,'Bielorrussia'),
	 (33,'Birmania'),
	 (34,'Bolivia'),
	 (35,'Bosnia E Herzegovina'),
	 (36,'Botsuana'),
	 (1,'Brasil'),
	 (37,'Brunei'),
	 (38,'Bulgaria'),
	 (39,'Burquina Faso'),
	 (40,'Burundi');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (41,'Butao'),
	 (42,'Cabo Verde'),
	 (43,'Camarões'),
	 (44,'Camboja'),
	 (45,'Canada'),
	 (46,'Catar'),
	 (47,'Cazaquistao'),
	 (48,'Chade'),
	 (49,'Chile'),
	 (50,'China');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (51,'Chipre'),
	 (52,'Clipperton Island'),
	 (53,'Colombia'),
	 (54,'Comores'),
	 (55,'Congo-Brazzaville'),
	 (56,'Congo-Kinshasa'),
	 (57,'Coral Sea Islands'),
	 (58,'Coreia Do Norte'),
	 (59,'Coreia Do Sul'),
	 (60,'Costa Do Marfim');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (61,'Costa Rica'),
	 (62,'Croacia'),
	 (63,'Cuba'),
	 (64,'Dhekelia'),
	 (65,'Dinamarca'),
	 (66,'Dominica'),
	 (67,'Egipto'),
	 (68,'Emiratos Arabes Unidos'),
	 (69,'Equador'),
	 (70,'Eritreia');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (71,'Eslovaquia'),
	 (72,'Eslovenia'),
	 (73,'Espanha'),
	 (74,'Estados Unidos'),
	 (75,'Estonia'),
	 (76,'Etiopia'),
	 (77,'Faroe'),
	 (78,'Fiji'),
	 (79,'Filipinas'),
	 (80,'Finlandia');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (81,'Franca'),
	 (82,'Gabao'),
	 (83,'Gambia'),
	 (84,'Gana'),
	 (85,'Gaza Strip'),
	 (86,'Georgia'),
	 (88,'Gibraltar'),
	 (89,'Granada'),
	 (90,'Grecia'),
	 (91,'Gronelandia');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (92,'Guame'),
	 (93,'Guatemala'),
	 (94,'Guernsey'),
	 (95,'Guiana'),
	 (96,'Guine'),
	 (97,'Guine Equatorial'),
	 (98,'Guine-Bissau'),
	 (99,'Haiti'),
	 (100,'Honduras'),
	 (101,'Hong Kong');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (102,'Hungria'),
	 (103,'Iemen'),
	 (104,'Ilha Bouvet'),
	 (105,'Ilha Do Natal'),
	 (106,'Ilha Norfolk'),
	 (107,'Ilhas Caimao'),
	 (108,'Ilhas Cook'),
	 (109,'Ilhas Dos Cocos'),
	 (110,'Ilhas Falkland'),
	 (111,'Ilhas Heard E Mcdonald');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (112,'Ilhas Marshall'),
	 (113,'Ilhas Salomao'),
	 (114,'Ilhas Turcas E Caicos'),
	 (115,'Ilhas Virgens Americanas'),
	 (116,'Ilhas Virgens Britanicas'),
	 (117,'India'),
	 (118,'Indian Ocean'),
	 (119,'Indonesia'),
	 (120,'Irao'),
	 (121,'Iraque');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (122,'Irlanda'),
	 (123,'Islandia'),
	 (124,'Israel'),
	 (125,'Italia'),
	 (126,'Jamaica'),
	 (127,'Jan Mayen'),
	 (128,'Japao'),
	 (129,'Jersey'),
	 (130,'Jibuti'),
	 (131,'Jordania');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (132,'Kuwait'),
	 (133,'Laos'),
	 (134,'Lesoto'),
	 (135,'Letonia'),
	 (136,'Libano'),
	 (137,'Liberia'),
	 (138,'Libia'),
	 (139,'Listenstaine'),
	 (140,'Lituania'),
	 (141,'Luxemburgo');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (142,'Macau'),
	 (143,'Macedonia'),
	 (144,'Madagascar'),
	 (145,'Malasia'),
	 (146,'Malavi'),
	 (147,'Maldivas'),
	 (148,'Mali'),
	 (149,'Malta'),
	 (150,'Man, Isle Of'),
	 (151,'Marianas Do Norte');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (152,'Marrocos'),
	 (153,'Mauricia'),
	 (154,'Mauritania'),
	 (155,'Mayotte'),
	 (156,'Mexico'),
	 (157,'Micronesia'),
	 (158,'Mocambique'),
	 (159,'Moldavia'),
	 (160,'Monaco'),
	 (161,'Mongolia');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (162,'Monserrate'),
	 (163,'Montenegro'),
	 (164,'Mundo'),
	 (165,'Namibia'),
	 (166,'Nauru'),
	 (167,'Navassa Island'),
	 (168,'Nepal'),
	 (169,'Nicaragua'),
	 (170,'Niger'),
	 (171,'Nigeria');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (172,'Niue'),
	 (173,'Noruega'),
	 (174,'Nova Caledonia'),
	 (175,'Nova Zelandia'),
	 (176,'Oma'),
	 (177,'Pacific Ocean'),
	 (178,'Paises Baixos'),
	 (179,'Palau'),
	 (180,'Panama'),
	 (181,'Papua-Nova Guine');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (182,'Paquistao'),
	 (183,'Paracel Islands'),
	 (184,'Paraguai'),
	 (185,'Peru'),
	 (186,'Pitcairn'),
	 (187,'Polinesia Francesa'),
	 (188,'Polonia'),
	 (189,'Porto Rico'),
	 (190,'Portugal'),
	 (191,'Quenia');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (192,'Quirguizistao'),
	 (193,'Quiribati'),
	 (194,'Reino Unido'),
	 (195,'Relistasa Centro-Africana'),
	 (196,'Relistasa Checa'),
	 (197,'Relistasa Dominicana'),
	 (198,'Romenia'),
	 (199,'Ruanda'),
	 (200,'Russia'),
	 (201,'Salvador');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (202,'Samoa'),
	 (203,'Samoa Americana'),
	 (204,'Santa Helena'),
	 (205,'Santa Lucia'),
	 (206,'Sao Cristovao E Neves'),
	 (207,'Sao Marinho'),
	 (208,'Sao Pedro E Miquelon'),
	 (209,'Sao Tome E Principe'),
	 (210,'Sao Vicente E Granadinas'),
	 (211,'Sara Ocidental');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (212,'Seicheles'),
	 (213,'Senegal'),
	 (214,'Serra Leoa'),
	 (215,'Servia'),
	 (216,'Singapura'),
	 (217,'Siria'),
	 (218,'Somalia'),
	 (219,'Southern Ocean'),
	 (220,'Spratly Islands'),
	 (221,'Sri Lanca');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (222,'Suazilandia'),
	 (223,'Sudao'),
	 (224,'Suecia'),
	 (225,'Suica'),
	 (226,'Suriname'),
	 (227,'Svalbard E Jan Mayen'),
	 (228,'Tailandia'),
	 (229,'Taiwan'),
	 (230,'Tajiquistao'),
	 (231,'Tanzania');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (233,'Territorios Austrais Franceses'),
	 (234,'Timor Leste'),
	 (235,'Togo'),
	 (236,'Tokelau'),
	 (237,'Tonga'),
	 (238,'Trindade E Tobago'),
	 (239,'Tunisia'),
	 (240,'Turquemenistao'),
	 (241,'Turquia'),
	 (242,'Tuvalu');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (244,'Uganda'),
	 (245,'Uniao Europeia'),
	 (246,'Uruguai'),
	 (247,'Usbequistao'),
	 (248,'Vanuatu'),
	 (249,'Vaticano'),
	 (250,'Venezuela'),
	 (251,'Vietname'),
	 (252,'Wake Island'),
	 (253,'Wallis E Futuna');
INSERT INTO listas.pais (id_pais,descricao) VALUES
	 (254,'West Bank'),
	 (255,'Zambia'),
	 (256,'Zimbabue'),
	 (257,'Guiana Francesa'),
	 (258,'Guiana Francesa');


INSERT INTO listas.estado (id_estado,descricao,uf) VALUES
	 (21,'Rondônia','RO'),
	 (1,'Acre','AC'),
	 (3,'Amazonas','AM'),
	 (22,'Roraima','RR'),
	 (14,'Pará','PA'),
	 (4,'Amapá','AP'),
	 (27,'Tocantins','TO'),
	 (10,'Maranhão','MA'),
	 (17,'Piauí','PI'),
	 (6,'Ceará','CE');
INSERT INTO listas.estado (id_estado,descricao,uf) VALUES
	 (20,'Rio Grande do Norte','RN'),
	 (15,'Paraíba','PB'),
	 (16,'Pernambuco','PE'),
	 (2,'Alagoas','AL'),
	 (25,'Sergipe','SE'),
	 (5,'Bahia','BA'),
	 (11,'Minas Gerais','MG'),
	 (8,'Espírito Santo','ES'),
	 (19,'Rio de Janeiro','RJ'),
	 (26,'São Paulo','SP');
INSERT INTO listas.estado (id_estado,descricao,uf) VALUES
	 (18,'Paraná','PR'),
	 (24,'Santa Catarina','SC'),
	 (23,'Rio Grande do Sul','RS'),
	 (12,'Mato Grosso do Sul','MS'),
	 (13,'Mato Grosso','MT'),
	 (9,'Goiás','GO'),
	 (7,'Distrito Federal','DF');