INSERT INTO tipo_participacao (descricao, valor) 
VALUES ('COMUNICANTE/VITIMA', 'CV'),
('CCOMUNICANTE', 'CM'),
('VITIMA', 'VT'),
('INVESTIGADO/INFRATOR', 'II');

INSERT INTO listas.tipo_moradia( descricao, valor ) 
VALUES ('RESIDENCIAL', 'RE'), 
('COMERCIAL', 'CO'),
('RESIDENCIAL/COMERCIAL', 'RC');

INSERT INTO public.funcao (descricao)
VALUES ('GESTOR'),
('AUTORIDADE POLICIAL'),
('REGISTRANTE'),
('DESENVOLVEDOR(A)'),
('CONSULTA');

INSERT INTO public.cargo (descricao) 
VALUES('DELEGADO DE POLÍCIA CIVIL'),
('INVESTIGADOR DE POLÍCIA CIVIL'),
('ESCRIVÃO(Ã) DE POLÍCIA CIVIL'),
('TÉCNICO ADMINISTRATIVO'),
('DESENVOLVEDOR(A)'),
('AGENTE ADMINISTRATIVO');

INSERT INTO listas.tipolocal (id_tipo_local,nome,valor) VALUES 
(1,'Não Informado','NI'),
(2,'Acampamento sem terra','AT'),
(3,'Aeroporto','AE'),
(4,'Agência dos Correios','AC'),
(5,'Aldeia Indígena','AI'),
(6,'Iambiente Virtual (Internet)','IN'),
(7,'Área Militar','AM'),
(8,'Assentamento Rural','AR'),
(9,'Associação','AS'),
(10,'Auto Escola','AU'),
(11,'Autódromo','AD'),
(12,'Banco','BC'),
(13,'Bar','BR'),
(14,'Café','CF'),
(15,'Cartório Público','CP'),
(16,'Carvoaria','CV'),
(17,'Casa de Abrigo','CA'),
(18,'Casa de Câmbio','CC'),
(19,'Casa de Guarda','CG'),
(20,'Casa Lotérica','CL'),
(21,'Casa Noturna (Boate)','CN'),
(22,'Cemitério','CM'),
(23,'Centro Comercial','CE'),
(24,'Centro de Educação Infantil','CI'),
(25,'Centro de Esporte e Lazer','CZ'),
(26,'Centro de Estética','CT'),
(27,'Clinica Hospitalar','CH'),
(28,'Clube Recreativo','CR'),
(29,'Comércio','CO'),
(30,'Comitê de Campanha Politica','CD'),
(31,'Condomínio Residencial','RC'),
(32,'Construção Abandonada','AB'),
(33,'Construção em Andamento','AO'),
(34,'Conveniência','NC'),
(35,'Delegacia de Polícia','DP'),
(36,'Depósito, Galpões, etc.','DG'),
(37,'Desconhecido','DS'),
(38,'Distribuidor Geral de Telefonia','DI'),
(39,'Embaixada, Consulado','EC'),
(40,'Embarcação Fluvial','EF'),
(41,'Ermo, Deserto','ED'),
(42,'Escola Estadual','EE'),
(43,'Escola Municipal','EM'),
(44,'Escola Particular','EP'),
(45,'Estação Ferroviária','ER'),
(46,'Estação Rodoviária','EO'),
(47,'Estacionamento Particular','EU'),
(48,'Estacionamento Publico','EB'),
(49,'Estádio esportivo','EI'),
(50,'Faculdade, Universidade','FU'),
(51,'Farmácia','FA'),
(52,'Favela, Aglomerado Habitacional','FV'),
(53,'Feira Pública','FP'),
(54,'Ferro Velho','FH'),
(55,'Financeira','FI'),
(56,'Floricultura, Viveiro de Mudas','FO'),
(57,'Frigorifico, Abatedouro','FT'),
(58,'Fronteira','FR'),
(59,'Garagem Residencial','GR'),
(60,'Guarita de Segurança','GS'),
(61,'Hospital Particular','HP'),
(62,'Hospital Público','HS'),
(63,'Hotel, Pousada','HH'),
(64,'Igreja, Templo, Mesquita','IT'),
(65,'Imóvel Abandonado','IA'),
(66,'Industria, Fábrica','IF'),
(67,'Joalheria','JO'),
(68,'Kartódromo','KA'),
(69,'Laboratório','LB'),
(70,'Lan House, Cyber Café','LH'),
(71,'Lanchonete','LA'),
(72,'Lava Jato','LJ'),
(73,'Madeireira, Serraria','MS'),
(74,'Mangue','MA'),
(75,'Mata, Floresta','MF'),
(76,'Motel','MO'),
(77,'Oficina Mecânica','OF'),
(78,'Ong, Instituição Filantrópica','ON'),
(79,'Ônibus, Van (intermunicipal)','OV'),
(80,'Ônibus, Van (Coletivo urbano)','OC'),
(81,'Ônibus, Van (transporte escolar)','OE'),
(82,'Ônibus, Van (turismo)','OT'),
(83,'Órgão Público','OP'),
(84,'Padaria, Confeitaria, etc.','PC'),
(85,'Parque de Diversões','PD'),
(86,'Parque','PQ'),
(87,'Pista de Pouso, etc.','PP'),
(88,'Pizzaria, Restaurante','PR'),
(89,'Ponto de Ônibus (urbano)','PT'),
(90,'Porto','PO'),
(91,'Posto de Combustível','PU'),
(92,'Posto de Saúde','PS'),
(93,'Praça','PA'),
(94,'Praia','PI'),
(95,'Penitenciária/Reformatório','PE'),
(96,'Propriedade Rural','PL'),
(97,'Propriedade Urbana','PN'),
(98,'Quilombo','QU'),
(99,'Reserva Ambiental','RA'),
(100,'Residência','RS'),
(101,'Rio, Lago','RI'),
(102,'Rodovia, Estrada','RO'),
(103,'Salão de Beleza','SB'),
(104,'Salão de Festas','SF'),
(105,'Shopping Center','SH'),
(106,'Sindicato, etc','SI'),
(107,'Supermercado','SU'),
(108,'Táxi','TX'),
(109,'Teatro/Eventos','TE'),
(110,'Terminal Rodoviário','TR'),
(111,'Terreno baldio','TB'),
(112,'Transporte por aplicativo','TA'),
(113,'Usina','US'),
(114,'Veículo de Transporte de Valores','VT'),
(115,'Veículo','VE'),
(116,'Via rural','VI'),
(117,'Via urbana','VU');